<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>06_Promise基本使用1</title>
</head>

<body>
    <!-- 
  1. 重要语法
      Promise(excute)构造函数
      Promise.prototype.then方法
  2. 基本编码流程
      1) 创建promise对象(pending状态), 指定执行器函数
      2) 在执行器函数中启动异步任务
      3) 根据结果做不同处理
          3.1) 如果成功了, 调用resolve(), 指定成功的value, 变为resolved状态
          3.2) 如果失败了, 调用reject(), 指定失败的reason, 变为rejected状态
      4) promise指定成功或失败的回调函数来获取成功的vlaue或失败的reason
  3. promise对象的状态
      1) 三个状态: 
          pending: 未确定的, 起始时的状态
          resolved: 解决/成功的, 调用resolve()后的状态
          rejected: 拒绝/失败的, 调用reject()后的状态
      2). 2种状态改变
          pending ==> resolved
          pending ==> rejected
      3). 状态只能改变一次
  -->
    <script>
        // 1) 创建promise对象(pending状态), 指定执行器函数
        const p = new Promise((resolve, reject) => { // 同步执行的执行器函数
            // 2) 在执行器函数中启动异步任务
            setTimeout(() => {
                // 3) 根据结果做不同处理
                const time = Date.now()

                //     3.1) 如果成功了, 调用resolve(), 指定成功的value, 变为resolved状态
                if (time % 2 == 1) {

                    resolve('成功的数据 ' + time)
                    console.log('resolve()之后')
                } else {//     3.2) 如果失败了, 调用reject(), 指定失败的reason, 变为rejected状态
                    reject('失败的数据 ' + time)
                }

            }, 1000);

        })

        // 4) promise指定成功或失败的回调函数来获取成功的vlaue或失败的reason
        p.then(
            value => {
                console.log('成功', value)
            },
            reason => {
                console.log('失败', reason)
            }
        )

        function timeout(ms) {
            return new Promise((resolve, reject) => {
                setTimeout(resolve(123), ms);
            });
        }

        timeout(100).then((value) => {
            console.log(value);
        });

        const someAsyncThing = function () {
            return new Promise(function (resolve, reject) {
                // 下面一行会报错，因为x没有声明
                resolve(x + 2);
            });
        };

        someAsyncThing().then(function () {
            console.log('everything is great');
        });

        setTimeout(() => { console.log(123) }, 2000);

        var promise2 = new Promise(function (resolve, reject) {
            setTimeout(function () {
                // throw 'Uncaught Exception!';
                reject('123222')
            }, 1000);
        });

        promise2.catch(function (e) {
            console.log(e);       //This is never called
        });
    </script>
</body>

</html>